name: Java CI/CD Pipeline (Auto-detect pom.xml)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  JAVA_VERSION: '17'
  JDK_DISTRO: 'temurin'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Find folder containing pom.xml and set as working directory
      - name: Locate pom.xml and set working directory
        id: pomdir
        run: |
          set -e
          pom_path=$(find . -name "pom.xml" | head -n 1)
          pom_dir=$(dirname "$pom_path")
          echo "pom_dir=$pom_dir" >> $GITHUB_OUTPUT
          echo "Located pom.xml at: $pom_path"

      # Step 3: Set up JDK
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JDK_DISTRO }}

      # Step 4: Build with Maven
      - name: Build with Maven
        run: mvn -B package
        working-directory: ${{ steps.pomdir.outputs.pom_dir }}

      # Step 5: Run tests
      - name: Run tests
        run: mvn test
        working-directory: ${{ steps.pomdir.outputs.pom_dir }}

      # Step 6: Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: ${{ steps.pomdir.outputs.pom_dir }}/target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 1: Deploy to server via SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/myapp
            git pull origin main
            systemctl restart tomcat
